name: "\U0001F4A1Feature request"
description: Suggest an idea to improve ARGAEL.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time for your feature requests! Please write a clear and concise description of the feature proposal.
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the ARGAEL is?
      options:
        - ARGAEL v1.0.x
        - ARGAEL v1.1.x
      default: 0
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Please write the motivation for the proposal.
        If your feature request is related to a problem, please describe a clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please write a detailed description of the new feature.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives (optional)
      description: Please write a clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (optional)
      description: Please add any other context or screenshots if you have.
    validations:
      required: false
